# Set Site Details
site_name: "Open Source Ontologies"
site_url: "http://www.opensourceontology.com"
blog_url: "http://blog.opensourceontology.com"
admin_email_name: "OpenSourceOntology"
admin_email_address: "opensourceontology@gmail.com"
version: "v0.1"

# Options
ajax_paging: true
show_social_media: true
require_email_activation: true
enable_throttler: false
show_morph: false

# About Page
site_description: "Open Source Ontology is a community site dedicated to tracking the best open ontology definitions."

# SEO Stuff
default_meta_keywords: "open source ontology owl rdf"
default_meta_description: "Open Source Ontology is a community site dedicated to tracking the best open ontology definitions."

# Tell a Friend
#tellafriend_subject: "Check out OpenSourceRails.com"
#tellafriend_body_intro: "OpenSourceRails.com is a gallery of the latest and greatest open source Ruby on Rails projects. Check it out: http://www.opensourcerails.com"
#tellafriend_body_message: "It features an easy to use browse gallery with screenshots plus community driven comments, ratings, and bookmarking."

# Paging Sizes
project_list_max: 25
projects_per_page: 6
bookmarks_per_page: 8

# Set Avatar Sizes
screenshot_sizes: 
  medium: "225x225#"
  thumb: "70x70#"

# Set default avatar
screenshot_default: "/images/default_screenshots/:style.png"

# Retarded Spam Question
spam_question: What is 3 plus 2?
spam_answer: 
  - "5"
  - "five"

